#!/bin/bash
# Automatic Fuzzing Harness Generator
# Analyzes your JavaScript code and generates appropriate fuzzing harnesses

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

if [ $# -lt 1 ]; then
    echo "Usage: $0 <javascript_file> [output_harness]"
    echo ""
    echo "This script analyzes your JavaScript code and generates a fuzzing harness."
    echo ""
    echo "Example:"
    echo "  $0 mylib.js fuzz_mylib.js"
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="${2:-fuzz_$(basename $INPUT_FILE)}"

if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: File not found: $INPUT_FILE"
    exit 1
fi

echo -e "${CYAN}╔═══════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Automatic Fuzzing Harness Generator    ║${NC}"
echo -e "${CYAN}╚═══════════════════════════════════════════╝${NC}"
echo ""

echo "Analyzing: $INPUT_FILE"
echo ""

# Analyze the JavaScript file for functions
echo -e "${YELLOW}Detecting functions...${NC}"

# Extract function definitions (simple regex - may not catch all cases)
FUNCTIONS=$(grep -E "^function\s+\w+|^\s*\w+\s*=\s*function|class\s+\w+" "$INPUT_FILE" | head -20 || true)

if [ -z "$FUNCTIONS" ]; then
    echo "No functions detected. Generating generic harness."
    HARNESS_TYPE="generic"
else
    echo -e "${GREEN}Found functions:${NC}"
    echo "$FUNCTIONS" | sed 's/^/  /'
    echo ""

    # Try to detect what the code does
    if grep -q "JSON.parse\|JSON.stringify" "$INPUT_FILE"; then
        echo -e "${GREEN}Detected: JSON processing${NC}"
        HARNESS_TYPE="json"
    elif grep -q "RegExp\|\.match\|\.test\|\.exec" "$INPUT_FILE"; then
        echo -e "${GREEN}Detected: Regular expression usage${NC}"
        HARNESS_TYPE="regexp"
    elif grep -q "parse\|Parse" "$INPUT_FILE"; then
        echo -e "${GREEN}Detected: Parser code${NC}"
        HARNESS_TYPE="parser"
    elif grep -q "validate\|Validate\|check\|Check" "$INPUT_FILE"; then
        echo -e "${GREEN}Detected: Validation code${NC}"
        HARNESS_TYPE="validator"
    elif grep -q "Array\|\.map\|\.filter\|\.reduce" "$INPUT_FILE"; then
        echo -e "${GREEN}Detected: Array operations${NC}"
        HARNESS_TYPE="array"
    else
        HARNESS_TYPE="generic"
    fi
fi

echo ""
echo -e "${YELLOW}Generating harness...${NC}"

# Generate harness based on detected type
cat > "$OUTPUT_FILE" << 'HEADER'
// Auto-generated Fuzzing Harness
// Generated by generate_harness.sh
HEADER

echo "// Source: $INPUT_FILE" >> "$OUTPUT_FILE"
echo "// Type: $HARNESS_TYPE" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

case $HARNESS_TYPE in
    json)
        cat >> "$OUTPUT_FILE" << 'EOF'
// JSON Processing Fuzzer
// This harness tests JSON parsing and processing functions

function fuzzJSONProcessing(input) {
    if (!input || input.length === 0) return;

    try {
        // Convert fuzzer input to string
        const jsonString = String.fromCharCode.apply(null, input);

        // TODO: Replace these with your actual function calls
        // Example patterns found in your code:

        // If you have a parseJSON function:
        // const result = parseJSON(jsonString);

        // If you have a validateJSON function:
        // const isValid = validateJSON(jsonString);

        // If you process JSON data:
        // const parsed = JSON.parse(jsonString);
        // const processed = processData(parsed);

    } catch (e) {
        // Expected errors for invalid JSON
    }
}

if (typeof FuzzerInput !== 'undefined') {
    fuzzJSONProcessing(FuzzerInput);
}
EOF
        ;;

    regexp)
        cat >> "$OUTPUT_FILE" << 'EOF'
// Regular Expression Fuzzer
// This harness tests regex processing functions

function fuzzRegExpProcessing(input) {
    if (!input || input.length < 2) return;

    try {
        // Extract pattern from fuzzer input
        const patternLen = Math.min(input[0] % 50, input.length - 1);
        const pattern = String.fromCharCode.apply(null, input.slice(1, 1 + patternLen));
        const testString = String.fromCharCode.apply(null, input.slice(1 + patternLen));

        // TODO: Replace with your actual function calls
        // Example patterns:

        // If you have a matchPattern function:
        // const result = matchPattern(pattern, testString);

        // If you have a validateRegex function:
        // const isValid = validateRegex(pattern);

        // If you process regex matches:
        // const re = new RegExp(pattern);
        // const matches = testString.match(re);
        // processMatches(matches);

    } catch (e) {
        // Expected errors for invalid regex
    }
}

if (typeof FuzzerInput !== 'undefined') {
    fuzzRegExpProcessing(FuzzerInput);
}
EOF
        ;;

    parser)
        cat >> "$OUTPUT_FILE" << 'EOF'
// Parser Fuzzer
// This harness tests parsing functions

function fuzzParser(input) {
    if (!input || input.length === 0) return;

    try {
        // Convert fuzzer input to string
        const inputString = String.fromCharCode.apply(null, input);

        // TODO: Replace with your actual parser function
        // Example patterns:

        // If you have a parse function:
        // const parsed = parse(inputString);

        // If you have a parseRequest function:
        // const request = parseRequest(inputString);

        // If you have a parseCommand function:
        // const command = parseCommand(inputString);

    } catch (e) {
        // Expected errors for invalid input
    }
}

if (typeof FuzzerInput !== 'undefined') {
    fuzzParser(FuzzerInput);
}
EOF
        ;;

    validator)
        cat >> "$OUTPUT_FILE" << 'EOF'
// Validator Fuzzer
// This harness tests validation functions

function fuzzValidator(input) {
    if (!input || input.length < 5) return;

    try {
        // Generate test data from fuzzer input
        const testData = {
            field1: String.fromCharCode.apply(null, input.slice(0, 20)),
            field2: (input[0] << 8) | input[1],
            field3: input[2] > 128,
            field4: Array.from(input.slice(3, 10))
        };

        // TODO: Replace with your actual validation function
        // Example patterns:

        // If you have a validate function:
        // const isValid = validate(testData);

        // If you have a validateInput function:
        // const result = validateInput(testData);

        // If you have specific field validators:
        // validateField1(testData.field1);
        // validateField2(testData.field2);

    } catch (e) {
        // Expected errors for invalid data
    }
}

if (typeof FuzzerInput !== 'undefined') {
    fuzzValidator(FuzzerInput);
}
EOF
        ;;

    array)
        cat >> "$OUTPUT_FILE" << 'EOF'
// Array Operations Fuzzer
// This harness tests array processing functions

function fuzzArrayOperations(input) {
    if (!input || input.length < 10) return;

    try {
        // Create array from fuzzer input
        const testArray = Array.from(input.slice(0, 100));

        // TODO: Replace with your actual function calls
        // Example patterns:

        // If you have an array processor:
        // const result = processArray(testArray);

        // If you have array transformation:
        // const transformed = transformArray(testArray);

        // If you have array validation:
        // const isValid = validateArray(testArray);

    } catch (e) {
        // Expected errors
    }
}

if (typeof FuzzerInput !== 'undefined') {
    fuzzArrayOperations(FuzzerInput);
}
EOF
        ;;

    generic|*)
        cat >> "$OUTPUT_FILE" << 'EOF'
// Generic Fuzzing Harness
// Customize this harness for your specific code

function fuzzGeneric(input) {
    if (!input || input.length === 0) return;

    try {
        // Strategy 1: String input
        const stringInput = String.fromCharCode.apply(null, input);

        // TODO: Call your functions here
        // Example:
        // yourFunction(stringInput);

        // Strategy 2: Binary input
        // const binaryInput = input;  // Already a Uint8Array
        // yourBinaryFunction(binaryInput);

        // Strategy 3: Structured input
        // const structured = {
        //     param1: input[0],
        //     param2: (input[1] << 8) | input[2],
        //     data: String.fromCharCode.apply(null, input.slice(3))
        // };
        // yourStructuredFunction(structured);

    } catch (e) {
        // Expected errors
    }
}

if (typeof FuzzerInput !== 'undefined') {
    fuzzGeneric(FuzzerInput);
}
EOF
        ;;
esac

echo -e "${GREEN}✓ Generated harness: $OUTPUT_FILE${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Review the harness and customize the TODO sections"
echo "2. Replace placeholder function calls with your actual functions"
echo "3. Combine with your source code:"
echo -e "   ${CYAN}cat $INPUT_FILE $OUTPUT_FILE > combined_fuzz.js${NC}"
echo ""
echo "4. Run the fuzzer:"
echo -e "   ${CYAN}./jsfuzzer --js=combined_fuzz.js${NC}"
echo ""
echo -e "${YELLOW}Tips:${NC}"
echo "  • Test each function in your code separately"
echo "  • Add multiple test strategies if your code has different features"
echo "  • Handle expected exceptions with try-catch"
echo "  • Start with short fuzzing runs to verify it works"
echo ""
